"""Reproduce the mini-zoo InterpBench leaderboard from the README.

Profiles 6 small open models (Pythia-160m, Pythia-410m, GPT-2, Mamba-130m,
Mamba-370m, Qwen2.5-0.5B) end-to-end on CPU. Kazdov-α is included only if
the local checkpoint is available; otherwise it's skipped.

Outputs:
- _research/mini_zoo_leaderboard.json   (machine-readable profiles)
- _research/mini_zoo_leaderboard.md      (human-readable table)

Run:
    python scripts/reproduce_mini_zoo.py
    python scripts/reproduce_mini_zoo.py --skip mamba-370m  # if memory-tight

CPU runtime: ~8-12 minutes (Mamba models dominate due to slow path on CPU).
GPU runtime: ~1-2 minutes if mamba-ssm is installed.
"""
from __future__ import annotations

import argparse
import json
import time
import traceback
from dataclasses import asdict
from pathlib import Path

import torch

from archscope import bench

ROOT = Path(__file__).parent.parent
KAZDOV_CHECKPOINT = Path.home() / "code" / "OriginalKazdov" / "_models" / "kazdov-98m-alpha"
OUT_DIR = ROOT / "_research"


# (display_name, hf_id, backend_hint, arch_family, extra kwargs for benchmark)
ZOO = [
    ("Pythia-160m",  "EleutherAI/pythia-160m",        "transformer", "transformer", {}),
    ("Pythia-410m",  "EleutherAI/pythia-410m",        "transformer", "transformer", {}),
    ("GPT-2",        "gpt2",                          "transformer", "transformer", {}),
    ("Mamba-130m",   "state-spaces/mamba-130m-hf",   "mamba",       "ssm",         {"ssm_layer": 12}),
    ("Mamba-370m",   "state-spaces/mamba-370m-hf",   "mamba",       "ssm",         {"ssm_layer": 24}),
    ("Qwen2.5-0.5B", "Qwen/Qwen2.5-0.5B",             "transformer", "transformer", {}),
]


def hf_tokenize(tok):
    def fn(texts):
        return tok(texts, return_tensors="pt", padding=True, truncation=True, max_length=32)
    return fn


def kazdov_tokenize(tok):
    def fn(texts):
        out = tok(texts, return_tensors="pt", padding=True, truncation=True, max_length=32)
        return {"input_ids": out["input_ids"], "attention_mask": out["attention_mask"].bool()}
    return fn


def run_hf_model(display, hf_id, hint, family, extra):
    from transformers import AutoModelForCausalLM, AutoTokenizer
    print(f"\n[loading] {display} ({hf_id})…")
    t0 = time.time()
    tok = AutoTokenizer.from_pretrained(hf_id)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    model = AutoModelForCausalLM.from_pretrained(hf_id, dtype=torch.float32)
    model.eval()
    print(f"  loaded in {time.time()-t0:.1f}s; running benchmark…")
    t1 = time.time()
    profile = bench.benchmark(
        model_name=hf_id, model=model, tokenizer=tok,
        backend_hint=hint, arch_family=family,
        tokenize_fn=hf_tokenize(tok),
        **extra,
    )
    profile.model_name = display  # shorter for the leaderboard
    print(f"  done in {time.time()-t1:.1f}s.")
    return profile


def run_kazdov():
    if not KAZDOV_CHECKPOINT.exists():
        return None
    # _kazdov_loader is a local-only helper that depends on the private
    # kazdov repo; it's not shipped to PyPI.
    import sys
    sys.path.insert(0, str(Path(__file__).parent))
    from _kazdov_loader import load_kazdov_checkpoint
    print(f"\n[loading] kazdov-α-98m (local: {KAZDOV_CHECKPOINT})…")
    model, tok = load_kazdov_checkpoint(str(KAZDOV_CHECKPOINT))
    profile = bench.benchmark(
        model_name="kazdov-α-98m", model=model, tokenizer=tok,
        backend_hint="kazdov", arch_family="hybrid",
        tokenize_fn=kazdov_tokenize(tok),
    )
    print(f"  done. induction={profile.induction_head_relative:.0f}×")
    return profile


def write_markdown(profiles, path):
    cols = ["model", "arch", "params", "L", "d", "sent", "math",
            "induct", "copy", "conc", "saeD", "saeR1", "ssmVar"]
    lines = [
        "# archscope — mini-zoo leaderboard",
        "",
        "Generated by `python scripts/reproduce_mini_zoo.py`.",
        "",
        "| " + " | ".join(cols) + " |",
        "|" + "|".join(["---"] * len(cols)) + "|",
    ]
    for p in profiles:
        params = f"{p.n_params/1e6:.0f}M"
        ssm = (f"{p.ssm_state_variance_ratio:.2f}"
               if p.ssm_state_variance_ratio == p.ssm_state_variance_ratio else "—")
        row = [
            p.model_name, p.arch_family, params, str(p.n_layers), str(p.hidden_dim),
            f"{p.probe_sentiment_auroc:.2f}",
            f"{p.probe_math_auroc:.2f}",
            f"{p.induction_head_relative:.0f}",
            f"{p.copy_accuracy:.0%}",
            f"{p.concentration_relative:.2f}",
            f"{p.sae_dense_recon:.3f}",
            f"{p.sae_rank1_recon:.3f}",
            ssm,
        ]
        lines.append("| " + " | ".join(row) + " |")
    path.write_text("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip", action="append", default=[],
                        help="Skip a model by display name (e.g. --skip Mamba-370m)")
    parser.add_argument("--skip-kazdov", action="store_true",
                        help="Skip the local kazdov-α even if checkpoint exists")
    args = parser.parse_args()

    OUT_DIR.mkdir(exist_ok=True)
    t_start = time.time()

    profiles = []
    for entry in ZOO:
        display, hf_id, hint, family, extra = entry
        if display in args.skip:
            print(f"[skipped] {display} (--skip)")
            continue
        try:
            profiles.append(run_hf_model(display, hf_id, hint, family, extra))
        except Exception as e:
            print(f"[error] {display}: {type(e).__name__}: {str(e)[:80]}")
            traceback.print_exc(limit=2)

    if not args.skip_kazdov:
        try:
            p = run_kazdov()
            if p is not None:
                profiles.append(p)
            else:
                print(f"[skipped] kazdov — checkpoint not found at {KAZDOV_CHECKPOINT}")
        except Exception as e:
            print(f"[error] kazdov: {type(e).__name__}: {str(e)[:80]}")

    if not profiles:
        print("\nNo profiles generated. Nothing to write.")
        return

    json_path = OUT_DIR / "mini_zoo_leaderboard.json"
    md_path = OUT_DIR / "mini_zoo_leaderboard.md"

    with open(json_path, "w") as f:
        json.dump([asdict(p) for p in profiles], f, indent=2, default=str)
    write_markdown(profiles, md_path)

    print(f"\nWrote:\n  {json_path}\n  {md_path}")
    print(f"Total runtime: {time.time()-t_start:.1f}s")


if __name__ == "__main__":
    main()
